export enum error{
    NOT_LABELED = "NOT_LABELED",
    INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT",
    EXISTING_CREDENTIALS = "EXISTING_CREDENTIALS",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    INTERNAL_SERVER = "INTERNAL_SERVER",
    URL_PARAMS_NOT_PROVIDED = "URL_PARAMS_NOT_PROVIDED",
    UNKNOWN_TYPE_ERROR = "UNKNOWN_TYPE_ERROR",
    NOT_FOUND = "NOT_FOUND",

}